### ISSUE TITLE
Fix errors in GUT tests using simulate on PlayerController.

### ISSUE THREAD

**Issue by DannyDarwiche** [Praqma/GodotDevOps#17]
## Description
When running tests on the PlayerController with Simulate( ), multiple errors show up in the console window. These are suspected to be related to the move_and_slide_with_snap function inside the player scripts _physics_process( ).

## Definition of done
- [x] No remaining errors when running tests.

**Comment by praqma-thi** [comment]
Options:
 - Ignore as they don't cause test failures
   - Let's not
 - Refactor so tests run without `simulate`/`move_and_slide`
   - Possibly, but it'd be nice to know how to use simulate best
 - Dive into docs on proper way of handling this situation
   - Should be done first anyway
 - Ask in GUT issue
   - Create a bare minimum/clean recreation of our problem. Ask a nicely formulated/formatted question in GUT issue
